version: '3.8'

services:
  backend:
    build:
      context: ./my-club-be
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: saulodev
      DB_NAME: myclub_db
    depends_on:
      - db

  frontend:
    build:
      context: ./my-club-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: saulodev
      MYSQL_DATABASE: myclub_db
    ports:
      - "3306:3306"
