version: '3.8'

services:
  backend:
    build:
      context: ./my-club-be   # Caminho relativo para o back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: saulodev
      DB_NAME: myclub_db
    depends_on:
      - db

  frontend:
    build:
      context: ./my-club-fe   # Caminho relativo para o front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: saulodev
      MYSQL_DATABASE: myclub
    ports:
      - "3306:3306"
