services:
  frontend:
    build:
      context: ./my-club-fe
      dockerfile: Dockerfile
    image: saulorodm/my-club-fe:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./my-club-be
      dockerfile: Dockerfile
    image: saulorodm/my-club-be:latest
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: saulodev
      DB_NAME: myclub_db
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: saulodev
      MYSQL_DATABASE: myclub_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
