version: '3.8'

services:
  frontend:
    image: saulorodm/my-club-fe
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backend

  backend:
    image: saulorodm/my-club-be
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: saulodev
      DB_NAME: myclub_db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: saulodev
      MYSQL_DATABASE: myclub_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db-data:
